services:
  consul:
    image: consul:1.14.6
    container_name: consul-server
    ports:
      - "8500:8500"
    volumes:
      - ./consul/consul-config.hcl:/consul/config/consul-config.hcl
    command: "agent -dev -config-file=/consul/config/consul-config.hcl"

  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - CONSUL_URL=http://consul-server:8500
    depends_on:
      - consul