services:
  consul:
    image: consul:1.14.6
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-ui", "-client=0.0.0.0"]
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  service_a:
    build:
      context: ./service_a
    environment:
      - PORT=8000
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      - consul
    ports:
      - "8000:8000"

  envoy_service_a:
    image: envoyproxy/envoy:v1.21.0
    volumes:
      - ./envoy/service_a.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - service_a
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8080:8080"

  service_b:
    build:
      context: ./service_b
    environment:
      - PORT=8001
      - CONSUL_HTTP_ADDR=http://consul:8500
    depends_on:
      - consul
    ports:
      - "8001:8001"

  envoy_service_b:
    image: envoyproxy/envoy:v1.21.0
    volumes:
      - ./envoy/service_b.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - service_b
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8081:8081"